In [1]:
import torch
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import os

import time
import torch.nn as nn
import matplotlib.pyplot as plt
import cv2 
import itertools

import csv
import torch
import torch.nn.functional as F
import torch.optim as optim
from torch.autograd import Variable
from torch.utils.data.sampler import SubsetRandomSampler


from vgg16_2 import VGG_16_2


import argparse
from data_loader_half_2 import get_loader
from data_loader_half_2 import get_dataset

import math

import numpy as np
import torch
import torch.nn as nn
import torch.utils.data
import torch.utils.data.distributed
import torchvision.transforms as transforms
import torchvision.datasets as datasets
import torchvision.models as models
import time
import shutil
import os
import torch.nn.functional as F

# Loading dataset

In [2]:
os.environ['CUDA_VISIBLE_DEVICES']='2'
celeba_image_dir = '/home/name/celeba/stargan/data/celeba/images'
attr_path = '/home/name/celeba/stargan/data/celeba/list_attr_celeba.txt'
id_path = '/home/name/celeba/stargan/data/celeba/identity_CelebA.txt'
selected_attrs = ['Black_Hair']
celeba_crop_size = 224
image_size = 224 
batch_size = 30
num_workers = 0
mode1 = 'train' #test or train
mode2 = 'test'
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu") #"cuda:0" if torch.cuda.is_available() else 
torch.set_default_tensor_type('torch.cuda.FloatTensor')


 



In [3]:
celeba_loader_train, data_train = get_loader(celeba_image_dir, attr_path, id_path, selected_attrs,celeba_crop_size, image_size, batch_size,'CelebA', mode1, num_workers)
celeba_loader_test, data_test = get_loader(celeba_image_dir, attr_path, id_path, selected_attrs,celeba_crop_size, image_size, batch_size,'CelebA', mode2, num_workers)

Finished preprocessing the CelebA dataset...
Finished preprocessing the CelebA dataset...


In [4]:
celeba_loader_test2, data_test2 = get_loader(celeba_image_dir, attr_path, id_path, selected_attrs,celeba_crop_size, image_size, 1,'CelebA', mode2, num_workers)

Finished preprocessing the CelebA dataset...


# Validate

In [6]:
def validate(model):
    model.to(device)
    model.eval()
    correct = 0
    size =0
    for im, labels in celeba_loader_test:
        im, labels = im.to(device), labels.to(device)
        labels = labels.long().squeeze(1)
        preds, _ = model(im)
        values, indices = preds.max(-1)
        correct += indices.eq(labels).sum()
        
        del im
        del preds
        
        del values
        
        print(correct)
        size += len(labels)
        del labels
        print(float(correct)/float(size))
        
    print(size)
    print(correct)


In [7]:
def validate_per_example(model):
    model.to(device)
    model.eval()
    correct = 0
    size =0
    for im, labels in celeba_loader_test2:
        im, labels = im.to(device), labels[:,0].to(device)
        labels = labels.long()
        preds, _ = model(im)
        values, indices = preds.max(-1)
        correct += indices.eq(labels).sum()

        
        del im
        del preds
        
        del values
        
        size += len(labels)
        del labels
        print(float(correct)/float(size))
        
    print(size)
    print(correct)
    return size,correct



In [8]:
def validate_per_example_mask(model, mask):
    model.to(device)
    model.eval()
    correct = 0
    size =0
    for im, labels in celeba_loader_test2:
        im, labels = im.to(device), labels[:,0].to(device)
        labels = labels.long()
        im = im
        preds, _ = model(im,mask)
        values, indices = preds.max(-1)
        correct += indices.eq(labels).sum()

        
        del im
        del preds
        
        del values
        
        size += len(labels)
        del labels
        print(float(correct)/float(size))
        
    print(size)
    print(correct)
    return size,correct



# Train

In [9]:
def train(model, criterion, optimizer, increase= False, coef=1):
    model.to(device)
    model.train()
    size = 0
    correcta = 0
    for i, (im, labels) in enumerate(celeba_loader_train):
        #if (i ==1):
         #   print (labels)
        print("iteration no", i)
        im, labels = im.to(device), labels.to(device)
        labels = labels.long().squeeze(1)
        
        
        
        optimizer.zero_grad()
        output,noisy = model(im)
        
        
        print(torch.mean(model.intermed.scales()))
        print(torch.max(model.intermed.scales()))
        print(torch.min(model.intermed.scales()))
        
        if (increase):
            #loss = criterion(output, labels) + coef* 1/(torch.mean(model.intermed.scales()) )
            print(labels.shape)
            print(labels)
            loss = criterion(output, labels) - coef* torch.log(torch.mean(model.intermed.scales()) ) + 10
            
        else:
            loss = criterion(output, labels)
        loss.backward()
        optimizer.step()
        print (loss, "loss")
        #preds = model(im)
        values, indices = output.max(-1)
        size += len(labels)
        correcta += indices.eq(labels).sum()
        correct = indices.eq(labels).sum()
        del im
        del labels
        del output
        del values
        del indices
        
        
        print(float(correcta)/float(size))
            
            
    print(correcta, "correct out of all")
    print(size)
    return correct, size
     
        





In [10]:
def train_mask(model, criterion, optimizer, mask, increase= False, coef=1):
    model.to(device)
    model.train()
    size = 0
    correcta = 0
    for i, (im, labels) in enumerate(celeba_loader_train):
        #if (i ==1):
         #   print (labels)
        print("iteration no", i)
        im, labels = im.to(device), labels[:,0].to(device)
        labels = labels.long()
        
        
        im = im 
        optimizer.zero_grad()
        output,noisy = model(im,mask)
        
        
        print(torch.mean(model.intermed.scales()))
        print(torch.max(model.intermed.scales()))
        print(torch.min(model.intermed.scales()))
        
        if (increase):
            print(labels.shape)
            print(labels)
            #loss = criterion(output, labels) + coef* 1/(torch.mean(model.intermed.scales()) )
            loss = criterion(output, labels) - coef* torch.log(torch.mean(model.intermed.scales()) ) + 10
        else:
            loss = criterion(output, labels)
        loss.backward()
        optimizer.step()
        print (loss, "loss")
        #preds = model(im)
        values, indices = output.max(-1)
        size += len(labels)
        correcta += indices.eq(labels).sum()
        correct = indices.eq(labels).sum()
        del im
        del labels
        del output
        del values
        del indices
        
        
        print(float(correcta)/float(size))
            
            
    print(correcta, "correct out of all")
    print(size)
    return correct, size
     
        





# Noisy Network

In [11]:

class NoisyActivation(nn.Module):
    def __init__(self,  given_locs, given_scales, min_scale, max_scale):
        super(NoisyActivation, self).__init__()
        size = given_scales.shape
        self.min_scale = min_scale
        self.max_scale = max_scale
        self.given_locs = given_locs 
        self.given_scales = given_scales
        self.locs = nn.Parameter(torch.Tensor(size).copy_(self.given_locs))         
        self.rhos = nn.Parameter(torch.ones(size)-5) #-inf


        self.normal = torch.distributions.normal.Normal(0,1)
        #self.rhos.requires_grad = False
        #self.locs.requires_grad = True
        
    def scales(self):
        return (1.0 +torch.tanh(self.rhos))/2*(self.max_scale-self.min_scale) +self.min_scale             
    
    def sample_noise(self, mask):
        epsilon = self.normal.sample(self.rhos.shape)*mask
        return  self.locs + self.scales()*epsilon
                                 
                               
                            
    def forward(self, input, mask):
        noise = self.sample_noise(mask)
        return (input)*mask + noise



class vgg_syn(nn.Module):

    def __init__(self, model_features, model_classifier, min_scale,max_scale, given_locs, given_scale):
        super(vgg_syn, self).__init__()
        

        self.intermed = NoisyActivation( given_locs, given_scale, min_scale, max_scale)
        self.model_pt2 =  torch.nn.Sequential(*(list(model_features)))
        self.model_pt3 = model_classifier
        #self.components = components
        for child in itertools.chain(self.model_pt2, self.model_pt3): #self.model_pt2 #(self.model_pt2, 
            for param in child.parameters():
                param.requires_grad = False
            if isinstance(child, nn.modules.batchnorm._BatchNorm):
                child.eval()
                child.affine = False
                child.track_running_stats = False
         
                                 
    def forward(self, img, mask):
                                 
        img = img
        x = self.intermed(img, mask)
        noisy = x.detach()
       
        x = self.model_pt2(x)                    
        x = x.view(img.size(0), -1)
        x = self.model_pt3(x)                                 

        return x, noisy
    
                                 
 

In [12]:

model = VGG_16_2()

model.load_state_dict(torch.load("vgg-hair-less-84l88",  map_location=device))


criterion = nn.NLLLoss()
mus = torch.zeros((3,224,224))
scale = torch.ones((3,224,224))*0.001
model_syn = vgg_syn(model.convnet, model.fc ,0.0,5 ,mus, scale )
model_syn.load_state_dict(torch.load("celeba-vgg-hair-avg-cloak", map_location=device))


<All keys matched successfully>

In [13]:
#mult_mask =  torch.ones(model_syn.intermed.rhos.shape)
mult_mask = torch.where(model_syn.intermed.scales()>4.5, torch.zeros(model_syn.intermed.scales().shape), torch.ones(model_syn.intermed.scales().shape))

In [14]:
criterion = nn.CrossEntropyLoss().to(device)

In [15]:
d = list(filter(lambda p: p.requires_grad, model_syn.parameters()))
print(len(d))

2


In [55]:
lr =  0.001  #

for epoch in range (1): # real
   
    optimizer = optim.Adam(filter(lambda p: p.requires_grad, model_syn.parameters()), lr=lr, weight_decay=0)
    cor, size = train_mask(model_syn, criterion, optimizer,mult_mask, True, 0.1)
    print (cor,size)
 
    validate_single_label(model_syn)
    


iteration no 0
tensor(4.8030, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1])
tensor(9.9007, grad_fn=<AddBackward0>) loss
0.7666666666666667
iteration no 1
tensor(4.8030, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 1, 1, 1, 0])
tensor(9.9321, grad_fn=<AddBackward0>) loss
0.7833333333333333
iteration no 2
tensor(4.8030, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
        1, 1, 0, 0, 0, 0])
tensor(9.9499, grad_fn=<AddBackward0>) loss
0.7666666666666667
iteration no 3
tensor(4.8030, grad_fn=<M

iteration no 26
tensor(4.8028, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 1, 0, 0])
tensor(9.9732, grad_fn=<AddBackward0>) loss
0.7888888888888889
iteration no 27
tensor(4.8028, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
        0, 1, 1, 0, 0, 0])
tensor(10.0378, grad_fn=<AddBackward0>) loss
0.7857142857142857
iteration no 28
tensor(4.8028, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
        0, 0, 0, 0, 0, 0])
tensor(10.0586, grad_fn=<AddBackward0>) loss
0.7816091954022989
iteration no 29
tensor(4.8028, grad

iteration no 52
tensor(4.8026, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
        0, 1, 0, 1, 0, 0])
tensor(9.8800, grad_fn=<AddBackward0>) loss
0.7710691823899372
iteration no 53
tensor(4.8026, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0])
tensor(9.9486, grad_fn=<AddBackward0>) loss
0.7709876543209877
iteration no 54
tensor(4.8026, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 1, 0, 0, 0, 1])
tensor(9.9632, grad_fn=<AddBackward0>) loss
0.7703030303030303
iteration no 55
tensor(4.8026, grad_f

iteration no 78
tensor(4.8025, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 1, 1])
tensor(10.0672, grad_fn=<AddBackward0>) loss
0.7746835443037975
iteration no 79
tensor(4.8025, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
        0, 0, 0, 0, 1, 0])
tensor(10.0377, grad_fn=<AddBackward0>) loss
0.77375
iteration no 80
tensor(4.8025, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        1, 0, 1, 0, 1, 0])
tensor(9.8591, grad_fn=<AddBackward0>) loss
0.7744855967078189
iteration no 81
tensor(4.8025, grad_fn=<MeanBa

iteration no 104
tensor(4.8024, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 1])
tensor(9.8981, grad_fn=<AddBackward0>) loss
0.7746031746031746
iteration no 105
tensor(4.8024, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 1, 1, 0, 0])
tensor(9.9816, grad_fn=<AddBackward0>) loss
0.7738993710691824
iteration no 106
tensor(4.8024, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
        0, 0, 1, 1, 0, 0])
tensor(9.8799, grad_fn=<AddBackward0>) loss
0.7744548286604361
iteration no 107
tensor(4.8024, gr

iteration no 130
tensor(4.8023, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0])
tensor(9.9179, grad_fn=<AddBackward0>) loss
0.7732824427480917
iteration no 131
tensor(4.8023, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
        0, 1, 0, 0, 0, 0])
tensor(9.9197, grad_fn=<AddBackward0>) loss
0.7732323232323233
iteration no 132
tensor(4.8023, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0])
tensor(9.9629, grad_fn=<AddBackward0>) loss
0.7736842105263158
iteration no 133
tensor(4.8023, gr

iteration no 156
tensor(4.8022, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0])
tensor(9.8465, grad_fn=<AddBackward0>) loss
0.7732484076433122
iteration no 157
tensor(4.8022, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
        0, 0, 0, 0, 1, 0])
tensor(9.9477, grad_fn=<AddBackward0>) loss
0.7729957805907173
iteration no 158
tensor(4.8022, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
        1, 1, 1, 0, 0, 1])
tensor(9.9042, grad_fn=<AddBackward0>) loss
0.7729559748427673
iteration no 159
tensor(4.8022, gr

iteration no 182
tensor(4.8021, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0])
tensor(9.9090, grad_fn=<AddBackward0>) loss
0.7735883424408014
iteration no 183
tensor(4.8021, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 0, 0])
tensor(9.9512, grad_fn=<AddBackward0>) loss
0.7735507246376812
iteration no 184
tensor(4.8021, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0])
tensor(10.0233, grad_fn=<AddBackward0>) loss
0.7735135135135135
iteration no 185
tensor(4.8020, g

tensor(4.8020, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 0, 0])
tensor(9.8585, grad_fn=<AddBackward0>) loss
0.7719298245614035
iteration no 209
tensor(4.8020, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
        0, 1, 0, 0, 1, 0])
tensor(9.9239, grad_fn=<AddBackward0>) loss
0.7725396825396825
iteration no 210
tensor(4.8020, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 1, 0, 0, 0])
tensor(9.8991, grad_fn=<AddBackward0>) loss
0.7726698262243286
iteration no 211
tensor(4.8020, grad_fn=<MeanBackwa

iteration no 234
tensor(4.8019, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 1, 1, 0, 0])
tensor(9.9138, grad_fn=<AddBackward0>) loss
0.7710638297872341
iteration no 235
tensor(4.8019, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0])
tensor(9.9757, grad_fn=<AddBackward0>) loss
0.771045197740113
iteration no 236
tensor(4.8019, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
        0, 0, 1, 1, 0, 0])
tensor(10.0995, grad_fn=<AddBackward0>) loss
0.7706047819971871
iteration no 237
tensor(4.8019, gr

iteration no 260
tensor(4.8018, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 1, 0, 0, 0])
tensor(10.0286, grad_fn=<AddBackward0>) loss
0.7694763729246488
iteration no 261
tensor(4.8018, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 1])
tensor(9.9858, grad_fn=<AddBackward0>) loss
0.7695928753180662
iteration no 262
tensor(4.8018, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
        1, 1, 0, 0, 0, 0])
tensor(10.0143, grad_fn=<AddBackward0>) loss
0.7697084917617237
iteration no 263
tensor(4.8018, 

iteration no 286
tensor(4.8017, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1])
tensor(9.9247, grad_fn=<AddBackward0>) loss
0.7694541231126597
iteration no 287
tensor(4.8017, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
        0, 0, 0, 1, 0, 0])
tensor(9.9161, grad_fn=<AddBackward0>) loss
0.7694444444444445
iteration no 288
tensor(4.8017, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
        1, 1, 1, 1, 0, 0])
tensor(9.9772, grad_fn=<AddBackward0>) loss
0.769434832756632
iteration no 289
tensor(4.8017, gra

iteration no 312
tensor(4.8016, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
        1, 0, 0, 0, 0, 0])
tensor(9.9289, grad_fn=<AddBackward0>) loss
0.7689030883919062
iteration no 313
tensor(4.8016, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0])
tensor(9.9217, grad_fn=<AddBackward0>) loss
0.7691082802547771
iteration no 314
tensor(4.8016, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
        0, 0, 0, 0, 0, 0])
tensor(9.8653, grad_fn=<AddBackward0>) loss
0.7694179894179894
iteration no 315
tensor(4.8016, gr

iteration no 338
tensor(4.8015, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0])
tensor(10.0227, grad_fn=<AddBackward0>) loss
0.7703048180924287
iteration no 339
tensor(4.8015, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
        0, 0, 0, 0, 0, 0])
tensor(9.9755, grad_fn=<AddBackward0>) loss
0.7701960784313725
iteration no 340
tensor(4.8015, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0])
tensor(9.7447, grad_fn=<AddBackward0>) loss
0.7705767350928642
iteration no 341
tensor(4.8015, g

iteration no 364
tensor(4.8014, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0])
tensor(10.0172, grad_fn=<AddBackward0>) loss
0.7700456621004567
iteration no 365
tensor(4.8014, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
        0, 0, 0, 1, 0, 1])
tensor(9.9130, grad_fn=<AddBackward0>) loss
0.770127504553734
iteration no 366
tensor(4.8014, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
        0, 0, 0, 1, 1, 0])
tensor(9.9743, grad_fn=<AddBackward0>) loss
0.7701180744777475
iteration no 367
tensor(4.8014, gr

iteration no 390
tensor(4.8014, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
        0, 0, 1, 0, 0, 0])
tensor(9.8579, grad_fn=<AddBackward0>) loss
0.769309462915601
iteration no 391
tensor(4.8014, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 0, 0])
tensor(9.8482, grad_fn=<AddBackward0>) loss
0.7694727891156462
iteration no 392
tensor(4.8014, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
        1, 1, 1, 0, 0, 0])
tensor(10.1088, grad_fn=<AddBackward0>) loss
0.7692111959287532
iteration no 393
tensor(4.8014, gr

iteration no 416
tensor(4.8014, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
        0, 1, 0, 0, 0, 0])
tensor(9.9315, grad_fn=<AddBackward0>) loss
0.7678657074340528
iteration no 417
tensor(4.8014, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
        0, 0, 1, 1, 0, 0])
tensor(9.9607, grad_fn=<AddBackward0>) loss
0.7677033492822967
iteration no 418
tensor(4.8014, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0])
tensor(9.8357, grad_fn=<AddBackward0>) loss
0.7680190930787589
iteration no 419
tensor(4.8014, gr

iteration no 442
tensor(4.8013, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 0, 0])
tensor(10.0249, grad_fn=<AddBackward0>) loss
0.7680963130173063
iteration no 443
tensor(4.8013, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0])
tensor(9.8722, grad_fn=<AddBackward0>) loss
0.7682432432432432
iteration no 444
tensor(4.8013, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0])
tensor(10.1056, grad_fn=<AddBackward0>) loss
0.7679400749063671
iteration no 445
tensor(4.8013, 

iteration no 468
tensor(4.8012, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        1, 0, 0, 0, 0, 0])
tensor(9.8719, grad_fn=<AddBackward0>) loss
0.768727789623312
iteration no 469
tensor(4.8012, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
        0, 0, 0, 0, 0, 1])
tensor(9.9671, grad_fn=<AddBackward0>) loss
0.768581560283688
iteration no 470
tensor(4.8012, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
        0, 0, 1, 0, 0, 0])
tensor(9.9458, grad_fn=<AddBackward0>) loss
0.7685774946921444
iteration no 471
tensor(4.8012, grad

tensor(9.9641, grad_fn=<AddBackward0>) loss
0.7676788124156545
iteration no 494
tensor(4.8011, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 1, 0])
tensor(9.9108, grad_fn=<AddBackward0>) loss
0.7679461279461279
iteration no 495
tensor(4.8011, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 0, 0, 1, 0])
tensor(9.9203, grad_fn=<AddBackward0>) loss
0.7679435483870968
iteration no 496
tensor(4.8011, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 1, 0])
tensor(9.9048, grad_fn=<AddBackwar

iteration no 520
tensor(4.8010, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 1])
tensor(9.9690, grad_fn=<AddBackward0>) loss
0.7682021753039028
iteration no 521
tensor(4.8010, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
        0, 0, 1, 0, 0, 0])
tensor(10.1395, grad_fn=<AddBackward0>) loss
0.767816091954023
iteration no 522
tensor(4.8010, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 1, 0, 0, 0, 0])
tensor(9.8347, grad_fn=<AddBackward0>) loss
0.7680688336520076
iteration no 523
tensor(4.8010, gr

iteration no 546
tensor(4.8009, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0])
tensor(9.9455, grad_fn=<AddBackward0>) loss
0.7675807434491164
iteration no 547
tensor(4.8009, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
        0, 0, 0, 1, 1, 0])
tensor(9.9973, grad_fn=<AddBackward0>) loss
0.7675182481751824
iteration no 548
tensor(4.8009, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0])
tensor(9.8990, grad_fn=<AddBackward0>) loss
0.7675774134790528
iteration no 549
tensor(4.8009, gr

iteration no 572
tensor(4.8008, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
        1, 0, 0, 0, 0, 1])
tensor(10.0185, grad_fn=<AddBackward0>) loss
0.7681210005817336
iteration no 573
tensor(4.8008, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0])
tensor(9.8032, grad_fn=<AddBackward0>) loss
0.7683507549361208
iteration no 574
tensor(4.8008, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
        1, 0, 1, 0, 0, 0])
tensor(9.9992, grad_fn=<AddBackward0>) loss
0.768231884057971
iteration no 575
tensor(4.8008, gr

iteration no 598
tensor(4.8007, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 1, 0])
tensor(9.8094, grad_fn=<AddBackward0>) loss
0.7685587089593767
iteration no 599
tensor(4.8007, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 0, 0])
tensor(9.9324, grad_fn=<AddBackward0>) loss
0.7685555555555555
iteration no 600
tensor(4.8007, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
        0, 0, 1, 0, 0, 1])
tensor(9.9627, grad_fn=<AddBackward0>) loss
0.7685524126455907
iteration no 601
tensor(4.8007, gr

tensor(4.8006, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
        0, 0, 1, 0, 1, 1])
tensor(10.1884, grad_fn=<AddBackward0>) loss
0.7692266666666666
iteration no 625
tensor(4.8006, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0])
tensor(9.9477, grad_fn=<AddBackward0>) loss
0.7693290734824281
iteration no 626
tensor(4.8006, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
        0, 0, 0, 1, 0, 0])
tensor(9.8555, grad_fn=<AddBackward0>) loss
0.7694311536416799
iteration no 627
tensor(4.8006, grad_fn=<MeanBackw

tensor(4.8005, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 1, 0])
tensor(9.8183, grad_fn=<AddBackward0>) loss
0.7700460829493088
iteration no 651
tensor(4.8005, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
        0, 0, 0, 1, 0, 0])
tensor(10.0483, grad_fn=<AddBackward0>) loss
0.7699897750511248
iteration no 652
tensor(4.8005, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0])
tensor(9.8411, grad_fn=<AddBackward0>) loss
0.7701378254211332
iteration no 653
tensor(4.8005, grad_fn=<MeanBackw

iteration no 676
tensor(4.8004, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
        0, 1, 0, 0, 0, 1])
tensor(10.0848, grad_fn=<AddBackward0>) loss
0.7697685869030034
iteration no 677
tensor(4.8004, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
        0, 0, 0, 0, 0, 0])
tensor(9.9930, grad_fn=<AddBackward0>) loss
0.7696656833824975
iteration no 678
tensor(4.8004, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0])
tensor(9.7919, grad_fn=<AddBackward0>) loss
0.7699067255768287
iteration no 679
tensor(4.8004, g

iteration no 702
tensor(4.8004, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0])
tensor(9.9533, grad_fn=<AddBackward0>) loss
0.7691322901849218
iteration no 703
tensor(4.8004, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        1, 0, 0, 1, 0, 0])
tensor(10.0634, grad_fn=<AddBackward0>) loss
0.7690814393939394
iteration no 704
tensor(4.8004, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1])
tensor(9.9444, grad_fn=<AddBackward0>) loss
0.7690780141843971
iteration no 705
tensor(4.8004, g

iteration no 728
tensor(4.8004, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
        0, 1, 1, 0, 1, 1])
tensor(9.9575, grad_fn=<AddBackward0>) loss
0.7689529035208048
iteration no 729
tensor(4.8004, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0])
tensor(9.9487, grad_fn=<AddBackward0>) loss
0.7690410958904109
iteration no 730
tensor(4.8003, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 1])
tensor(9.9548, grad_fn=<AddBackward0>) loss
0.7691290469676243
iteration no 731
tensor(4.8003, gr

iteration no 754
tensor(4.8003, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
        1, 0, 1, 1, 1, 0])
tensor(9.9129, grad_fn=<AddBackward0>) loss
0.7683443708609271
iteration no 755
tensor(4.8003, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0])
tensor(9.8542, grad_fn=<AddBackward0>) loss
0.7684744268077601
iteration no 756
tensor(4.8003, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
        0, 0, 1, 0, 1, 1])
tensor(9.9579, grad_fn=<AddBackward0>) loss
0.7684280052840159
iteration no 757
tensor(4.8003, gr

iteration no 780
tensor(4.8003, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
        1, 0, 1, 0, 0, 0])
tensor(9.9621, grad_fn=<AddBackward0>) loss
0.7681177976952624
iteration no 781
tensor(4.8003, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 1, 1, 0, 1, 1])
tensor(9.9946, grad_fn=<AddBackward0>) loss
0.768073316283035
iteration no 782
tensor(4.8003, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0])
tensor(9.9603, grad_fn=<AddBackward0>) loss
0.7680289484887186
iteration no 783
tensor(4.8002, gra

iteration no 806
tensor(4.8001, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 1, 0, 0])
tensor(9.9546, grad_fn=<AddBackward0>) loss
0.7684014869888476
iteration no 807
tensor(4.8001, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0])
tensor(9.9943, grad_fn=<AddBackward0>) loss
0.7683993399339935
iteration no 808
tensor(4.8001, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
        1, 1, 0, 0, 0, 0])
tensor(9.9574, grad_fn=<AddBackward0>) loss
0.7683559950556242
iteration no 809
tensor(4.8001, gr

iteration no 832
tensor(4.8000, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
        1, 1, 0, 0, 0, 0])
tensor(9.9623, grad_fn=<AddBackward0>) loss
0.7699079631852741
iteration no 833
tensor(4.8000, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
        0, 0, 0, 1, 0, 0])
tensor(9.9379, grad_fn=<AddBackward0>) loss
0.7699440447641887
iteration no 834
tensor(4.7999, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 1])
tensor(9.7789, grad_fn=<AddBackward0>) loss
0.770059880239521
iteration no 835
tensor(4.7999, gra

iteration no 858
tensor(4.7999, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
        0, 0, 1, 1, 1, 1])
tensor(9.9374, grad_fn=<AddBackward0>) loss
0.7696546371750097
iteration no 859
tensor(4.7999, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
        1, 1, 0, 0, 0, 0])
tensor(9.9893, grad_fn=<AddBackward0>) loss
0.7695348837209303
iteration no 860
tensor(4.7999, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 1])
tensor(9.8989, grad_fn=<AddBackward0>) loss
0.7695702671312428
iteration no 861
tensor(4.7998, gr

iteration no 884
tensor(4.7998, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 1])
tensor(9.9246, grad_fn=<AddBackward0>) loss
0.7691902071563088
iteration no 885
tensor(4.7998, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
        0, 0, 1, 0, 0, 0])
tensor(10.0108, grad_fn=<AddBackward0>) loss
0.7691497366440933
iteration no 886
tensor(4.7998, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 1, 0])
tensor(9.9630, grad_fn=<AddBackward0>) loss
0.7691469372416385
iteration no 887
tensor(4.7998, g

iteration no 910
tensor(4.7997, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1,
        0, 0, 0, 0, 0, 0])
tensor(9.9911, grad_fn=<AddBackward0>) loss
0.7692279546286133
iteration no 911
tensor(4.7997, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
        0, 0, 1, 0, 0, 0])
tensor(9.8547, grad_fn=<AddBackward0>) loss
0.7693347953216374
iteration no 912
tensor(4.7997, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0])
tensor(9.9914, grad_fn=<AddBackward0>) loss
0.7692953632712669
iteration no 913
tensor(4.7997, gr

iteration no 936
tensor(4.7996, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 1, 1])
tensor(9.9906, grad_fn=<AddBackward0>) loss
0.7692280327285663
iteration no 937
tensor(4.7996, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 1, 0])
tensor(10.0039, grad_fn=<AddBackward0>) loss
0.7691897654584222
iteration no 938
tensor(4.7996, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
        1, 0, 0, 1, 1, 0])
tensor(10.0859, grad_fn=<AddBackward0>) loss
0.7690095846645367
iteration no 939
tensor(4.7996, 

iteration no 962
tensor(4.7996, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
        0, 0, 0, 1, 0, 0])
tensor(10.0212, grad_fn=<AddBackward0>) loss
0.7690896503980617
iteration no 963
tensor(4.7996, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 1, 0])
tensor(9.9161, grad_fn=<AddBackward0>) loss
0.7690525587828493
iteration no 964
tensor(4.7996, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
        1, 0, 1, 0, 0, 0])
tensor(10.0097, grad_fn=<AddBackward0>) loss
0.7689464594127806
iteration no 965
tensor(4.7996, 

iteration no 988
tensor(4.7996, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
        1, 0, 0, 0, 0, 0])
tensor(9.9245, grad_fn=<AddBackward0>) loss
0.7691607684529828
iteration no 989
tensor(4.7996, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
        1, 1, 0, 0, 0, 0])
tensor(9.9284, grad_fn=<AddBackward0>) loss
0.7691245791245791
iteration no 990
tensor(4.7995, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0])
tensor(9.9234, grad_fn=<AddBackward0>) loss
0.76912209889001
iteration no 991
tensor(4.7995, grad

iteration no 1014
tensor(4.7995, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
        0, 0, 0, 1, 0, 0])
tensor(9.8816, grad_fn=<AddBackward0>) loss
0.76935960591133
iteration no 1015
tensor(4.7995, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 1, 0])
tensor(9.9244, grad_fn=<AddBackward0>) loss
0.7694225721784776
iteration no 1016
tensor(4.7995, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 1, 0])
tensor(9.8395, grad_fn=<AddBackward0>) loss
0.7694526384791871
iteration no 1017
tensor(4.7995, 

tensor(9.9191, grad_fn=<AddBackward0>) loss
0.7695512820512821
iteration no 1040
tensor(4.7993, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        1, 1, 1, 0, 0, 0])
tensor(9.9465, grad_fn=<AddBackward0>) loss
0.7695485110470701
iteration no 1041
tensor(4.7993, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
        1, 0, 0, 0, 1, 0])
tensor(10.0151, grad_fn=<AddBackward0>) loss
0.7695457453614843
iteration no 1042
tensor(4.7993, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0,
        0, 1, 0, 0, 1, 1])
tensor(10.0685, grad_fn=<AddBa

tensor(4.7993, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0])
tensor(10.0219, grad_fn=<AddBackward0>) loss
0.7697906904092471
iteration no 1067
tensor(4.7992, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 1, 0, 0, 0, 0])
tensor(9.8488, grad_fn=<AddBackward0>) loss
0.769912609238452
iteration no 1068
tensor(4.7992, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0])
tensor(9.8769, grad_fn=<AddBackward0>) loss
0.770065481758653
iteration no 1069
tensor(4.7992, grad_fn=<MeanBack

tensor(9.9127, grad_fn=<AddBackward0>) loss
0.7701770451770452
iteration no 1092
tensor(4.7992, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
        0, 0, 1, 1, 1, 0])
tensor(9.9045, grad_fn=<AddBackward0>) loss
0.770204330588594
iteration no 1093
tensor(4.7992, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
        0, 1, 0, 0, 0, 0])
tensor(10.0218, grad_fn=<AddBackward0>) loss
0.7701401584399756
iteration no 1094
tensor(4.7992, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
        1, 0, 0, 0, 1, 0])
tensor(9.8712, grad_fn=<AddBack

tensor(4.7990, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0])
tensor(9.9118, grad_fn=<AddBackward0>) loss
0.7707179028894846
iteration no 1119
tensor(4.7990, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0])
tensor(10.0120, grad_fn=<AddBackward0>) loss
0.7707142857142857
iteration no 1120
tensor(4.7990, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0,
        1, 0, 0, 0, 0, 0])
tensor(9.9311, grad_fn=<AddBackward0>) loss
0.7707701457032412
iteration no 1121
tensor(4.7990, grad_fn=<MeanBa

tensor(9.9620, grad_fn=<AddBackward0>) loss
0.7709498834498835
iteration no 1144
tensor(4.7989, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1,
        0, 0, 0, 1, 0, 1])
tensor(9.9832, grad_fn=<AddBackward0>) loss
0.7708879184861718
iteration no 1145
tensor(4.7989, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
        1, 0, 1, 0, 1, 1])
tensor(10.0308, grad_fn=<AddBackward0>) loss
0.770826061663758
iteration no 1146
tensor(4.7989, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 1, 0])
tensor(9.9303, grad_fn=<AddBack

tensor(4.7989, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
        0, 1, 0, 1, 1, 0])
tensor(9.9771, grad_fn=<AddBackward0>) loss
0.7703387418161116
iteration no 1171
tensor(4.7989, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
        0, 1, 0, 0, 0, 1])
tensor(9.9658, grad_fn=<AddBackward0>) loss
0.770278725824801
iteration no 1172
tensor(4.7989, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
        1, 0, 1, 0, 1, 0])
tensor(9.9772, grad_fn=<AddBackward0>) loss
0.7702472293265132
iteration no 1173
tensor(4.7989, grad_fn=<MeanBack

tensor(9.7918, grad_fn=<AddBackward0>) loss
0.770819397993311
iteration no 1196
tensor(4.7988, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
        0, 0, 0, 1, 0, 0])
tensor(10.1279, grad_fn=<AddBackward0>) loss
0.7706766917293233
iteration no 1197
tensor(4.7988, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 1, 0, 1, 0, 0])
tensor(9.9655, grad_fn=<AddBackward0>) loss
0.7706455203116305
iteration no 1198
tensor(4.7988, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0])
tensor(9.8380, grad_fn=<AddBack

tensor(4.7986, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
        0, 1, 1, 0, 1, 0])
tensor(9.9064, grad_fn=<AddBackward0>) loss
0.7710820387026438
iteration no 1223
tensor(4.7986, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0])
tensor(10.0231, grad_fn=<AddBackward0>) loss
0.7710511982570806
iteration no 1224
tensor(4.7986, grad_fn=<MeanBackward0>)
tensor(5.0000, grad_fn=<MaxBackward1>)
tensor(0.0003, grad_fn=<MinBackward1>)
torch.Size([30])
tensor([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 1])
tensor(9.9334, grad_fn=<AddBackward0>) loss
0.7711020408163265
iteration no 1225
tensor(4.7986, grad_fn=<MeanBa

KeyboardInterrupt: 

In [16]:
validate_per_example_mask(model_syn, mult_mask) 

1.0
1.0
1.0
1.0
1.0
1.0
1.0
0.875
0.7777777777777778
0.7
0.7272727272727273
0.75
0.7692307692307693
0.7857142857142857
0.8
0.8125
0.8235294117647058
0.7777777777777778
0.7894736842105263
0.8
0.8095238095238095
0.8181818181818182
0.8260869565217391
0.8333333333333334
0.84
0.8461538461538461
0.8518518518518519
0.8571428571428571
0.8620689655172413
0.8666666666666667
0.8709677419354839
0.875
0.8787878787878788
0.8823529411764706
0.8857142857142857
0.8888888888888888
0.8918918918918919
0.8947368421052632
0.8974358974358975
0.9
0.9024390243902439
0.9047619047619048
0.8837209302325582
0.8863636363636364
0.8888888888888888
0.8913043478260869
0.8936170212765957
0.8958333333333334
0.8979591836734694
0.88
0.8823529411764706
0.8846153846153846
0.8867924528301887
0.8888888888888888
0.8727272727272727
0.8571428571428571
0.8596491228070176
0.8620689655172413
0.847457627118644
0.85
0.8524590163934426
0.8548387096774194
0.8571428571428571
0.859375
0.8615384615384616
0.8636363636363636
0.86567164179104

0.7463312368972747
0.7468619246861925
0.7453027139874739
0.7458333333333333
0.7463617463617463
0.7448132780082988
0.7453416149068323
0.7458677685950413
0.7463917525773196
0.7469135802469136
0.7453798767967146
0.7459016393442623
0.7464212678936605
0.746938775510204
0.7474541751527495
0.7479674796747967
0.7484787018255578
0.7489878542510121
0.7474747474747475
0.7479838709677419
0.7484909456740443
0.748995983935743
0.7474949899799599
0.746
0.7465069860279441
0.7470119521912351
0.7475149105367793
0.748015873015873
0.7465346534653465
0.7450592885375494
0.7455621301775148
0.7460629921259843
0.7465618860510805
0.7470588235294118
0.7475538160469667
0.748046875
0.7485380116959064
0.7490272373540856
0.7495145631067961
0.75
0.7504835589941973
0.750965250965251
0.7514450867052023
0.7519230769230769
0.7504798464491362
0.7490421455938697
0.7476099426386233
0.7480916030534351
0.7485714285714286
0.747148288973384
0.7476280834914611
0.7462121212121212
0.7466918714555766
0.7471698113207547
0.74764595103

0.7586580086580087
0.7589189189189189
0.7591792656587473
0.7583603020496225
0.7586206896551724
0.7578040904198062
0.7580645161290323
0.7583243823845328
0.7585836909871244
0.7588424437299035
0.7580299785867237
0.7572192513368984
0.7564102564102564
0.7566702241195304
0.7569296375266524
0.7561235356762513
0.7553191489361702
0.7555791710945803
0.7558386411889597
0.7560975609756098
0.7563559322033898
0.7555555555555555
0.7547568710359408
0.7550158394931362
0.7542194092827004
0.7534246575342466
0.7536842105263157
0.7539432176656151
0.7542016806722689
0.7534102833158447
0.7536687631027253
0.7539267015706806
0.75418410041841
0.754440961337513
0.7546972860125261
0.7549530761209593
0.7552083333333334
0.7554630593132154
0.7546777546777547
0.754932502596054
0.7551867219917012
0.755440414507772
0.7556935817805382
0.7559462254395036
0.756198347107438
0.7564499484004128
0.756701030927835
0.756951596292482
0.757201646090535
0.7564234326824255
0.75564681724846
0.7558974358974359
0.7561475409836066
0.75

0.7631195335276968
0.763292061179898
0.7634643377001455
0.7629090909090909
0.7630813953488372
0.7632534495279594
0.7634252539912917
0.7635968092820885
0.763768115942029
0.7639391745112237
0.76410998552822
0.7642805495300072
0.7644508670520231
0.7646209386281588
0.7647907647907648
0.7642393655371305
0.7644092219020173
0.7638588912886969
0.7633093525179856
0.7634795111430626
0.7636494252873564
0.7638190954773869
0.7639885222381636
0.7634408602150538
0.7628939828080229
0.7630637079455977
0.7632331902718169
0.7626876340243031
0.7628571428571429
0.7630264097073519
0.7624821683309557
0.7626514611546685
0.7621082621082621
0.7615658362989324
0.7617354196301565
0.7619047619047619
0.7620738636363636
0.7622427253371186
0.7624113475177305
0.7625797306874557
0.7627478753541076
0.7629157820240623
0.7630834512022631
0.7632508833922261
0.7634180790960452
0.7635850388143967
0.7637517630465445
0.7639182522903453
0.7640845070422535
0.7642505277973258
0.7644163150492265
0.7645818692902319
0.76474719101123

0.7565934065934066
0.756727073036793
0.756860592755214
0.7569939659901261
0.7571271929824561
0.7572602739726028
0.7568455640744798
0.7569786535303776
0.7571115973741794
0.7572443958447239
0.7573770491803279
0.7575095576187876
0.75764192139738
0.7577741407528642
0.757360959651036
0.7574931880108992
0.7576252723311547
0.7577572128470332
0.7578890097932536
0.758020663404024
0.7581521739130435
0.7582835415535035
0.758414766558089
0.7585458491589799
0.7586767895878525
0.7588075880758808
0.7589382448537378
0.758527341635084
0.7581168831168831
0.7577068685776095
0.7578378378378379
0.7579686655861696
0.7580993520518359
0.7582298974635726
0.7583603020496225
0.7584905660377359
0.7580818965517241
0.7582121701669359
0.7583423035522067
0.7584722969338354
0.7586021505376344
0.7587318645889307
0.7588614393125671
0.7584541062801933
0.7580472103004292
0.7581769436997319
0.7583065380493034
0.7584359935725763
0.7585653104925053
0.7581594435527019
0.758288770053476
0.757883484767504
0.7580128205128205
0.7

0.7601410934744268
0.7602468047598061
0.7599118942731278
0.7600176133861735
0.7601232394366197
0.7602287725472944
0.7598944591029023
0.76
0.7601054481546573
0.7602108036890646
0.7603160667251976
0.7599824484422992
0.7600877192982456
0.7601928978518194
0.7602979842243646
0.7604029785370127
0.760507880910683
0.7606126914660831
0.7607174103237095
0.7608220376038478
0.7609265734265734
0.7610310179117519
0.7611353711790393
0.761239633347883
0.7613438045375218
0.7610117749672918
0.7611159546643418
0.7612200435729848
0.7608885017421603
0.760992599042229
0.7606614447345518
0.7603305785123967
0.7604347826086957
0.7605388961321164
0.760642919200695
0.7607468519322622
0.7604166666666666
0.7605206073752712
0.7606244579358196
0.7602947550931947
0.7603986135181976
0.7605023819835427
0.7606060606060606
0.76070964950238
0.7608131487889274
0.7604842196281885
0.7601555747623163
0.7602591792656588
0.7603626943005182
0.7604661199827363
0.7601380500431406
0.7602414833980163
0.7603448275862069
0.76044808272

0.7612380250552689
0.7609576427255985
0.7606774668630338
0.7607655502392344
0.7608535688005886
0.7609415226186098
0.7610294117647058
0.7611172363101801
0.7612049963262307
0.7612926918839515
0.7613803230543319
0.7614678899082569
0.7611885546588408
0.7612761276127613
0.7609970674486803
0.7610846463906192
0.7608058608058608
0.7608934456243135
0.7609809663250366
0.761068422978412
0.7611558156547183
0.7612431444241317
0.7613304093567251
0.7614176105224698
0.7615047479912345
0.7615918218327857
0.7616788321167883
0.7617657789128055
0.761852662290299
0.7619394823186293
0.7616618075801749
0.7617486338797814
0.7618353969410051
0.7619220968329087
0.7620087336244541
0.7620953073845035
0.7621818181818182
0.7622682660850599
0.7619912790697675
0.7620777333817653
0.7621641249092229
0.7618874773139745
0.761611030478955
0.7616974972796517
0.76178390137781
0.7618702428416093
0.7615942028985507
0.761680550525172
0.7617668356263577
0.7614911328266377
0.7615774240231549
0.7616636528028933
0.7617498192335502

0.7628083491461101
0.7628833386025925
0.7626422250316056
0.7627172195892575
0.7627921667719519
0.7628670666245658
0.7629419191919192
0.7630167245187757
0.762776025236593
0.7628508356985179
0.7629255989911727
0.762685156003782
0.7627599243856332
0.7628346456692914
0.7629093198992444
0.762669184765502
0.7627438640654499
0.7628184963825102
0.7628930817610063
0.7629676202452059
0.7627278441231929
0.7628023876845743
0.7625628140703518
0.7623233908948195
0.7623979912115505
0.7621587700031377
0.7619196988707654
0.7616807776732518
0.7617554858934169
0.761830147289251
0.7619047619047619
0.7619793297839023
0.7620538509705698
0.7621283255086072
0.7618898623279099
0.7619643415702221
0.7620387742338962
0.7621131603626133
0.761875
0.7619493908153702
0.7617114303560275
0.7617858257883234
0.7615480649188514
0.761622464898596
0.7616968184653774
0.7617711256626131
0.7618453865336658
0.7619196011218448
0.761993769470405
0.7620678916225475
0.7618306351183064
0.7619047619047619
0.7619788425637835
0.7620528

0.7626696206037109
0.762735326688815
0.7625242181013009
0.762589928057554
0.762655601659751
0.7627212389380531
0.7625103677080454
0.7622996130458817
0.7620889748549323
0.7621546961325967
0.7622203811101905
0.7622860298177803
0.7623516422853989
0.7624172185430463
0.7622068965517241
0.7622724765581909
0.7623380204025365
0.7624035281146637
0.762193441719482
0.762258953168044
0.7623244285320848
0.7623898678414097
0.7624552711257914
0.7625206384149698
0.7623108665749656
0.7623762376237624
0.7624415727247732
0.7625068719076415
0.7625721352019785
0.7626373626373626
0.7627025542433398
0.7624931356397584
0.7625583310458414
0.7623490669593853
0.7624142661179698
0.7622051563357104
0.7622703591993419
0.7620614035087719
0.7621266100301453
0.7619178082191781
0.7619830183511367
0.7617743702081051
0.7618395839036408
0.7619047619047619
0.761969904240766
0.7620350109409191
0.7621000820344545
0.762165117550574
0.7622301175184477
0.7622950819672131
0.7623600109259765
0.7624249044238122
0.7624897624897625


0.7663873829472647
0.7664449371766445
0.766256157635468
0.7660674710662398
0.7658788774002954
0.7659365001230618
0.765994094488189
0.7660516605166051
0.7661091982292179
0.7661667076469142
0.7659783677482792
0.7660358810518555
0.7658476658476658
0.7659051830017195
0.7657170923379175
0.7655290940338817
0.7653411880216003
0.7651533742331288
0.7649656526005888
0.7647780230561687
0.7645904855321236
0.7646481980877666
0.7647058823529411
0.764518500367557
0.7645761881430672
0.7643889297085477
0.7642017629774731
0.7640146878824969
0.7640724424865394
0.7641301688279912
0.7639432485322897
0.7640009782342871
0.7638141809290954
0.7638719139574676
0.7639296187683284
0.7639872953823601
0.7640449438202247
0.764102564102564
0.76416015625
0.7639736392482304
0.7640312347486579
0.7640888021468651
0.7639024390243903
0.7639600097537186
0.7640175524134568
0.7638313429198148
0.7638888888888888
0.76394640682095
0.7637603507062835
0.76381787192598
0.7638753651411879
0.7636894621562424
0.7637469586374696
0.7638

0.7634265423879272
0.7634790326159308
0.7633096716947648
0.7633621645597694
0.7634146341463415
0.7634670804699624
0.7632978723404256
0.7633503212940395
0.7634027470093044
0.7634551495016612
0.7632860938883969
0.7633384990037636
0.7633908809207613
0.7634432396547909
0.7634955752212389
0.7635478876354789
0.7633790358248562
0.7634313508733142
0.7634836427939876
0.7635359116022099
0.7635881573133009
0.7636403799425668
0.7636925795053003
0.7637447560167807
0.7637969094922737
0.7636283381152064
0.7636804942630185
0.7637326273990734
0.7637847375385972
0.7638368246968027
0.7638888888888888
0.7639409301300418
0.7637725870427501
0.7638246309759859
0.7638766519823789
0.7639286500770756
0.7639806252752092
0.7640325775918996
0.7640845070422535
0.7639163916391639
0.7639683238011439
0.764020233120739
0.7638522427440633
0.7639041547592877
0.763956043956044
0.7640079103493738
0.7638400702987698
0.7638919393806282
0.7639437856829161
0.7639956092206367
0.7640474100087796
0.7640991880623217
0.764150943396

0.7650151668351871
0.7648604933279418
0.7649080250656963
0.7647534357316087
0.7648009698929077
0.7648484848484849
0.7648959806099778
0.7649434571890146
0.7647890167575206
0.7648364957610012
0.7646821392532795
0.764729620661824
0.7645753479927375
0.7646228317870108
0.764670296430732
0.7647177419354839
0.7647651683128401
0.7648125755743652
0.7646584726979649
0.7647058823529411
0.764551863041289
0.7645992750704793
0.7646466680088585
0.7644927536231884
0.7645401489233246
0.7645875251509054
0.7644337155501911
0.7642799678197908
0.7643273677860446
0.7643747486932047
0.7644221105527638
0.7644694533762058
0.764516777175005
0.7645640819606268
0.764611367744527
0.7644578313253012
0.764505119453925
0.7643516659975913
0.7643989564519366
0.764446227929374
0.7642928786359077
0.764340152426795
0.7641868859033487
0.7640336808340016
0.7640809781519342
0.7641282565130261
0.7641755159286716
0.7640224358974359
0.7640696975766073
0.7641169403283941
0.7639639639639639
0.7640112089671738
0.7640584350610367
0

0.7621259988849656
0.7621701969528056
0.7620286085825748
0.7618870728083209
0.7619312906220984
0.7619754920163386
0.7618340449229627
0.7618782479584262
0.7619224345889776
0.7619666048237477
0.7620107586718605
0.7620548961424333
0.7620990172445763
0.7621431219873934
0.7621872103799815
0.7622312824314307
0.7622753381508245
0.7623193775472398
0.7623634006297463
0.7624074074074074
0.7624513978892797
0.7624953720844132
0.7623542476401999
0.7623982235381199
0.7622571692876966
0.7623011468738439
0.762345108193083
0.7623890532544378
0.7624329820669254
0.7624768946395564
0.7623359822583626
0.7621951219512195
0.7622390541289489
0.7622829700775766
0.7623268698060942
0.7623707533234859
0.7624146206387299
0.7624584717607974
0.7625023066986529
0.7623616236162362
0.7624054602471869
0.7622648469199558
0.7623086852295777
0.7623525073746312
0.7623963133640553
0.7624401032067821
0.7624838769117376
0.7625276344878408
0.7625713759440044
0.7624309392265194
0.7624746823789358
0.7625184094256259
0.76237806000

0.7614962251201098
0.7615371418768228
0.7614065180102916
0.761447436117304
0.7614883401920439
0.7615292302417281
0.7615701062735687
0.7616109682947729
0.7616518163125429
0.7616926503340757
0.7617334703665639
0.7616030142147628
0.7616438356164383
0.7616846430405753
0.7617254364943512
0.7615950710251583
0.7616358658453114
0.7616766467065869
0.7617174136161478
0.7617581665811527
0.7617989056087552
0.7618396307061036
0.7618803418803419
0.7619210391386088
0.7617908407382091
0.7618315393815137
0.7618722241202597
0.7619128949615713
0.7619535519125683
0.7618234591087587
0.7618641174462274
0.7619047619047619
0.7617747440273037
0.7616447705169767
0.7616854315933128
0.7617260787992496
0.7615961800818554
0.7616368286445013
0.7616774633481077
0.7617180841997614
0.7615882753919564
0.7616288975975465
0.7616695059625213
0.7617101004939534
0.7617506811989101
0.7617912480844543
0.7618318011576438
0.7618723404255319
0.7619128658951668
0.7619533775735919
0.7619938754678462
0.761864262629699
0.761904761904

0.7625876354365838
0.7626254580213477
0.7626632685568653
0.7627010670488932
0.7627388535031847
0.7626174176086611
0.7626552053486151
0.7626929810600032
0.7625716104392107
0.7626093874303899
0.7624880687241489
0.7625258469858438
0.7624045801526718
0.7624423596756241
0.7623211446740858
0.7623589254490543
0.762396694214876
0.762275544255522
0.7623133142675564
0.762351072279587
0.7623888182973316
0.7622677465459743
0.762305493807558
0.7623432290839816
0.7623809523809524
0.762418663704174
0.7624563630593463
0.7623353958432493
0.7623730964467005
0.7624107850911974
0.7624484617824294
0.7624861265260822
0.7625237793278377
0.7625614201933746
0.7624405705229794
0.7624782126445888
0.7625158428390367
0.7625534611119912
0.7625910674691162
0.7626286619160728
0.762666244458518
0.7627038151021054
0.762741373852485
0.7627789207153031
0.7628164556962025
0.7628539788008226
0.762733312242961
0.7626126838526016
0.7624920936116382
0.7625296442687747
0.7625671830540626
0.762604709973131
0.7624841972187105
0.

0.7625353370034221
0.7625706634930081
0.7626059794734493
0.7626412849494348
0.7625278810408922
0.7625631876300922
0.7624498290471236
0.7624851367419738
0.7625204339426364
0.762407132243685
0.7624424305452384
0.76232917409388
0.7623644734887866
0.7623997623997624
0.762286562731997
0.7623218527315915
0.7623571322547128
0.7622439893143366
0.7621308799525152
0.7620178041543026
0.7620531078475004
0.7620884010679324
0.7621236838202581
0.7620106761565836
0.7620459599703484
0.7620812333234509
0.7619682821994961
0.76185536455246
0.7618906504667358
0.7619259259259259
0.761813064731151
0.7618483412322274
0.7618836072856509
0.7619188628960616
0.7618060695780903
0.7618413262285376
0.761876572443392
0.7619118082272862
0.7619470335848498
0.7619822485207101
0.7620174530394912
0.7620526471458149
0.7619399674700577
0.7619751626256653
0.762010347376201
0.7620455217262785
0.7620806856805084
0.7621158392434988
0.7620032501107993
0.7620384047267356
0.7620735489587949
0.7621086828115771
0.761996161228407
0.7

0.7616124982563817
0.7616457461645746
0.7615395342351137
0.7614333519241495
0.7614666109019936
0.7614998606077502
0.7615331010452961
0.7615663322185061
0.761460220147694
0.7614934522151017
0.7615266750243767
0.7615598885793872
0.7615930928839995
0.7616262879420774
0.7615202561603787
0.7614142538975501
0.7614474599860821
0.7613414973559699
0.7613747043272575
0.7612687813021702
0.7613019891500904
0.7613351877607789
0.7612293144208038
0.7612625139043382
0.7612957041568191
0.7613288851820962
0.7612230715774844
0.7611172873818788
0.7611504793664027
0.761183662128369
0.761216835671621
0.76125
0.7612831551173448
0.7611774507081366
0.7610717756490352
0.7611049416990561
0.7611380985426787
0.7611712461837358
0.761204384626058
0.7612375138734739
0.76127063392981
0.7613037447988904
0.7613368464845375
0.7613699389905713
0.7614030223208097
0.761297477127807
0.7613305613305613
0.7613636363636364
0.7612581405015935
0.7612912164034359
0.7613242831417094
0.7613573407202217
0.761390389142778
0.7614234284

0.7610607850859918
0.7610921501706485
0.7611235070219189
0.7611548556430446
0.7610549796614617
0.7609551298871687
0.7609864882592156
0.7608866736621196
0.7607868852459017
0.7606871230002623
0.7607185000655565
0.7607498689040377
0.7607812295189409
0.7608125819134993
0.7608439260909449
0.7607442348008385
0.7607755797196384
0.760806916426513
0.7608382449246889
0.7608695652173914
0.7609008773078434
0.7609321811992669
0.7609634768948815
0.7609947643979058
0.7610260437115561
0.7609264590421355
0.7608269004317676
0.760858189429618
0.7608894702419883
0.76092074287209
0.7609520073231333
0.7609832635983264
0.761014511700876
0.7609150326797386
0.7609462815318259
0.7608468374281233
0.7608780870246962
0.7609093284557095
0.7609405617243632
0.7609717868338558
0.7608724043359018
0.7607730477931575
0.7608042825434129
0.7608355091383812
0.7608667275812557
0.7608979378752284
0.7607986428291792
0.7608298538622129
0.7607305936073059
0.7607618053743804
0.7607930089996087
0.7606937923839332
0.760724996740122

0.7606053088563632
0.7606349993798834
0.7606646825396826
0.7606943583384997
0.7607240267790727
0.7607536878641379
0.7607833415964304
0.7608129879786838
0.7608426270136307
0.760872258704002
0.7609018830525273
0.7609315000619349
0.7609611097349517
0.7609907120743034
0.7608964834076275
0.7609260864182246
0.7609556820995296
0.7609852704542641
0.7608910891089109
0.7609206781338943
0.7609502598366741
0.7609798342199678
0.7608857001484414
0.7609152752009894
0.760944842938412
0.7608507481142575
0.7608803165182987
0.7609098776115713
0.7609394313967861
0.7609689778766531
0.7609985170538803
0.761028048931175
0.7610575735112429
0.7610870907967882
0.7611166007905138
0.7611461034951217
0.7611755989133119
0.7612050870477837
0.7612345679012346
0.7611405999259351
0.7611700814613676
0.7611995557201037
0.7612290227048372
0.7612584824182603
0.7612879348630643
0.761317380041939
0.7613468179575728
0.7613762486126526
0.7612823674475956
0.7613117987917642
0.7613412228796844
0.7613706397140392
0.76140004929751

0.7609027859409898
0.7609308885754584
0.7609589846045364
0.7609870740305523
0.7610151568558337
0.7610432330827067
0.7609538353107013
0.7608644585388772
0.7608925425719318
0.7609206200093941
0.760948690853587
0.7608593566564922
0.7608874281018899
0.7607981220657277
0.7608261941086727
0.7607369162168505
0.76076498885369
0.760793054903801
0.7608211143695015
0.7608491672531081
0.7608772135569368
0.7607879924953096
0.7608160393950053
0.7607268464243845
0.7607548939163052
0.7607829348335677
0.7608109691784836
0.760838996953363
0.7608670181605155
0.7608950328022493
0.7609230408808715
0.7609510423986883
0.7609790373580044
0.7610070257611241
0.7609179253014869
0.7608288457035823
0.7608568418588318
0.7608848314606742
0.7609128145114101
0.7609407910133396
0.7608517608517609
0.7608797379503978
0.7609077085039185
0.7609356725146199
0.7608466845982926
0.7608746492048644
0.7609026072723021
0.7609305588028993
0.760958503798948
0.7609864422627396
0.7608975108098632
0.7609254498714653
0.7609533824044865

0.7604515984797675
0.7603666033307254
0.7603933839964238
0.7604201586769471
0.7603351955307263
0.7603619707295274
0.7603887399463807
0.7603038087791801
0.7603305785123967
0.76035734226689
0.7603841000446628
0.7602992073238808
0.7602143335565975
0.7602410983368679
0.7602678571428572
0.7602946099765651
0.760321356839991
0.7603480977351333
0.7602632753235163
0.7602900167317346
0.7603167521748829
0.760343481654957
0.7603702051739518
0.7603969227338611
0.7604236343366778
0.7604503399843942
0.7603655818100757
0.7603922879750362
0.7604189881880989
0.7604456824512534
0.7604723707664884
0.7604990531357915
0.7605257295611495
0.7605524000445484
0.7605790645879733
0.7604943770181495
0.7605210420841684
0.7605477012134031
0.7604630454140695
0.760378408458542
0.7604050745604274
0.7604317347279403
0.760347129506008
0.7603737901880075
0.7602892102335929
0.760204649093538
0.7602313167259787
0.760257978427666
0.7602846342005781
0.7603112840466926
0.7603379279679857
0.7602534178059354
0.7602800622360525
0

0.7606819392647842
0.7607074366077136
0.7607329285181634
0.7607584149978697
0.7607838960485674
0.7608093716719915
0.7607283569374933
0.7607538330494037
0.7607793037368253
0.7608047690014903
0.7607237892496008
0.7607492550021285
0.7607747153346813
0.7606937646307725
0.7607192254495159
0.7606382978723404
0.7606637591745559
0.7606892150606254
0.760714665532277
0.7607401105912378
0.7607655502392344
0.7607909844779928
0.7608164133092378
0.7607355442176871
0.7607609735359762
0.7607863974495218
0.7608118159600468
0.7608372290692733
0.7608626367789227
0.7607818143190992
0.7608072225172597
0.7608326253186066
0.7607518317935649
0.7607772350817583
0.7608026329758998
0.7607218683651805
0.760747266744507
0.7607726597325408
0.7607980473309987
0.7608234295415959
0.7608488063660478
0.7608741778060684
0.7608995438633712
0.7609249045396691
0.760844204051331
0.760763520678685
0.7607888877107412
0.7608142493638677
0.7608396056397753
0.7608649565401738
0.7607843137254902
0.7608096651123357
0.76083501112641

0.7606924643584522
0.7607168312799104
0.760741193239666
0.7607655502392344
0.7607899022801303
0.7608142493638677
0.7607368206798291
0.7607611682100336
0.7607855107855108
0.7608098484077729
0.7608341810783317
0.760858508798698
0.7607811228641171
0.760703752669582
0.760728086231442
0.7606507371631926
0.7606750711671411
0.7606994002236455
0.7607237243342143
0.7606464071551987
0.760670731707317
0.7606950513159232
0.7607193659825239
0.7607436757086254
0.7607679804957335
0.760792280345353
0.7608165752589884
0.760739311465421
0.7607636068237206
0.7607878972484516
0.7608121827411167
0.760836463303218
0.7608607389362566
0.760783517710342
0.7608077937893242
0.760832064941654
0.7608563311688312
0.7608805924723546
0.7609048488537229
0.7609291003144335
0.7609533468559838
0.7609775884798702
0.7610018251875887
0.7609246679509277
0.7609489051094891
0.7609731373542828
0.7609973646868031
0.7610215871085436
0.7610458046209971
0.7610700172256561
0.7610942249240121
0.7611184277175564
0.7610413290113452
0.7

0.7615054602184087
0.7615287120990543
0.7615519594462858
0.7615752022614289
0.7615984405458089
0.7616216743007505
0.7616449035275775
0.7616681282276138
0.7615939204988309
0.7616171456405261
0.7616403662575492
0.7616635823512223
0.7616867939228672
0.761612620508326
0.7616358325219085
0.7616590400155778
0.7616822429906542
0.7616080989000292
0.7616313023165272
0.761654501216545
0.7616776956014013
0.7617008854724141
0.761724070830901
0.7617472516781788
0.7617704280155642
0.7617935998443731
0.7618167671659211
0.7617426820966644
0.7616686114352392
0.7615945551774429
0.7615205133190744
0.7615436959268981
0.7615668740279938
0.7615900476236758
0.7615160349854228
0.7615392090175882
0.7615623785464438
0.7614883901680753
0.7615115601321159
0.7615347255949491
0.7614607614607615
0.7614839273574827
0.7615070887550981
0.761530245654918
0.7614563106796116
0.7614794680128143
0.7615026208503203
0.7615257691934388
0.7615489130434783
0.7615720524017467
0.7614981564137395
0.761424274764723
0.761350407450523

0.7601045458788388
0.7601269367183124
0.7601493233784414
0.7600783874580067
0.7600074647755902
0.7600298563164769
0.7600522436794477
0.7600746268656716
0.760003730995243
0.7600261145308711
0.7600484938916348
0.760070869078702
0.76
0.7600223755360805
0.760044746900345
0.7599739000745712
0.7599962717867462
0.7600186393289842
0.7600410027024509
0.7600633619083116
0.7600857169477313
0.7601080678218745
0.76003726129483
0.7600596125186289
0.7600819595790258
0.7601043024771839
0.7601266412142658
0.7601489757914339
0.7601713062098501
0.7601936324706758
0.7602159545750722
0.7602382725241995
0.7602605863192182
0.760282895961288
0.7603052014515679
0.760327502791217
0.7603497999813936
0.7603720930232558
0.7603943819179612
0.7603236607142857
0.760345949967451
0.7603682350753208
0.7602975360297536
0.7603198214949796
0.7603421028167705
0.7602714259155977
0.7602937075936426
0.7603159851301116
0.7603382585261593
0.7602676082512544
0.760289882003159
0.7602192493496841
0.7601486298188574
0.76017090841538

0.7600286532951289
0.760050138776972
0.7599820948970457
0.7600035807000268
0.7599355531686359
0.7598675378143739
0.7598890281009486
0.759910514541387
0.7599319971367215
0.7598640064418001
0.75979602791197
0.7598175149834511
0.7598389982110912
0.7597710401574099
0.7597925236988017
0.7598140033980149
0.7598354792560801
0.7598569512740277
0.7597890219917754
0.7597211048538483
0.7597425813371469
0.7597640539815891
0.7596961572832887
0.7597176302385846
0.7597390993566834
0.7597605646386134
0.7597820260854029
0.7598034836980795
0.7598249374776705
0.7597570777886934
0.759778531880693
0.7597999821412627
0.7598214285714285
0.7597535934291582
0.7596857703981432
0.7597072212800143
0.7597286683327383
0.7597501115573405
0.7597715509548456
0.7597929865262782
0.7597251962883654
0.7597466321705773
0.759678858162355
0.7597002943537597
0.7596325365679629
0.7596539730669758
0.7596754057428214
0.7596968345965225
0.7597182596291013
0.7597396808415797
0.7597610982349795
0.7597825118103217
0.7598039215686274

0.7609387088455256
0.760959257349149
0.7609798023205845
0.7609144035751118
0.7609349488699837
0.7609554906341296
0.7608901108342642
0.7609106529209622
0.7609311914783953
0.7609517265074729
0.7609722580091042
0.7609927859841978
0.7610133104336625
0.7610338313584063
0.7610543487593372
0.7610748626373627
0.76109537299339
0.7611158798283262
0.7610505536005493
0.761071060762101
0.7610057495923797
0.7610262570791144
0.7610467610467611
0.7610672614962252
0.7610877584284121
0.7611082518442271
0.761128741744575
0.7611492281303602
0.7611697110024869
0.761190190361859
0.76121066620938
0.7612311385459534
0.7612516073724818
0.761272072689868
0.7612925344990144
0.7612272883099075
0.76124775044991
0.7612682090831191
0.7612886642104362
0.7613091158327622
0.761329563950998
0.7613500085660442
0.7613704496788009
0.7613908872901679
0.7614113214010448
0.7614317520123309
0.7613665553557668
0.7613869863013699
0.7613218046400136
0.76125663413799
0.7611914747924334
0.7612119137281753
0.7611467693624304
0.76108

0.7601521793069225
0.7600893152497519
0.7601091540560655
0.7601289895816107
0.7601488218272013
0.7601686507936508
0.7601884764817723
0.760208298892379
0.7601454665674849
0.7601652892561983
0.760185108668705
0.7602049248058173
0.7602247376683466
0.7601619299405156
0.7601817430813713
0.760201552948951
0.7601387626992648
0.7601585728444004
0.7600957965149888
0.7601156069364162
0.7601354140863678
0.7600726552179656
0.7600924626434409
0.7601122667987452
0.7600495253817582
0.7600693298118191
0.7600891309730131
0.7601089288661496
0.7601287234920373
0.7601485148514852
0.7601683029453016
0.7601880877742947
0.7602078693392724
0.7602276476410426
0.7601649484536083
0.760184727032822
0.7602045023501278
0.7602242744063324
0.7602440432022426
0.7602638087386645
0.7602835710164042
0.7603033300362677
0.7603230857990604
0.7602604252513598
0.7602801812937783
0.7602175346077785
0.7602372909285655
0.7602570439940682
0.7602767938050911
0.7602965403624382
0.7602339181286549
0.7602536649645857
0.76027340854813

0.759406887755102
0.7594260661618174
0.7594452415112386
0.7594644138040966
0.7594038890659867
0.7593433739740219
0.7592828685258964
0.7593020476456059
0.759321223709369
0.7592607344857802
0.759279910785407
0.7592990840302668
0.7593182542210896
0.7592577845026678
0.7592769549291288
0.759216498128832
0.759156050955414
0.7591752249024759
0.7591147906384333
0.7591339648173207
0.7591531359439669
0.7591723040191006
0.7591914690434506
0.7591310575316305
0.7591502227880331
0.7591693849948286
0.7591885441527446
0.7591281520960942
0.7590677696468342
0.7590073968026724
0.7590265627485288
0.7589662027833002
0.758985368956743
0.7590045320823726
0.7590236921609159
0.7590428491930996
0.7590620031796502
0.7590811541212941
0.759100302018757
0.7590399745688627
0.7590591226954864
0.7590782677791021
0.7590179564595583
0.7590371017716692
0.7590562440419447
0.7590753832711097
0.7590945194598888
0.7591136526090064
0.7591327827191868
0.7591519097911538
0.7591710338256312
0.7591107582373958
0.7591298825023817


(12700, tensor(9643))